### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PwrSrg** [torifat/jetbrains-icls-editor#2]
Hey, ran across this this morning and wanted to try it out, but I am unable to get it working.

Despite the complete lack of ANY documentation or startup instructions, I was able to get all of the modules installed, and compile the Webpack bundle, but all I get is a blank white page.

Have you tried to run this lately?  Did it ever run?

**Comment by torifat** [comment]
Hey sorry, I didn't actually continue the development of it :(
